repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies: 
          - types-requests
          - types-python-dateutil
          - types-pyyaml
        exclude: ^tests/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
        exclude: ^notebooks/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=5120]
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-commits-lint
        args: [--config=.commitlintrc.yaml]\

        