DATASET_PATH: "ml/datasets/cyber_threats.csv"
TARGET_COLUMN: "attack_type"
REQUIRED_COLUMNS: ["duration", "protocol_type", "src_bytes", "dst_bytes"]
TEST_SIZE: 0.2
RANDOM_STATE: 42
STRATIFY_SPLIT: True
N_ESTIMATORS: 200
MAX_DEPTH: None
CLASS_WEIGHT: "balanced"


monitoring:
  reference_stats_path: "ml/models/deployment_packages/latest/reference_stats.json"
  drift_threshold: 0.05
  performance_window: 1000
  performance_decay_threshold: 0.05
  enable_scheduled_checks: true
  check_interval_hours: 24

mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "cybershield_production"