[tool.black]
line-length = 100
target-version = ["py310"]
include = '\.pyi?$'

[tool.mypy]
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--cov=ml --cov-report=html --cov-report=term-missing"
testpaths = ["tests"]

[tool.ruff]
select = ["E", "F", "B", "I", "N", "D", "UP"]
ignore = ["D203"]
line-length = 100